.TH "es.etg.daw.prog.mercadaw.model.exception.ExportException" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.exception.ExportException
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.exception\&.MercaDAWException\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
