.TH "es.etg.daw.prog.mercadaw.view.sistema.ExportarDatosViewController" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.view.sistema.ExportarDatosViewController
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.ViewController\fP\&.
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static final String \fBNOMBRE_VENTANA\fP = 'Seleccionar Destino'"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
Vusta de la exportación de datos del sistema\&. 
.PP
\fBAutor\fP
.RS 4
Erik Herrera Llamas 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
