.TH "es.etg.daw.prog.mercadaw.model.entities.empleados.Contratable" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.empleados.Contratable
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "double \fBgetSalarioNeto\fP ()"
.br
.ti -1c
.RI "double \fBgetSalarioBruto\fP ()"
.br
.ti -1c
.RI "double \fBgetAportaciones\fP ()"
.br
.ti -1c
.RI "double \fBgetIndemnizacion\fP (\fBTipoDespido\fP tipo)"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static final double \fBSUELDO_EMPLE\fP = 1000"
.br
.ti -1c
.RI "static final double \fBSUELDO_REPON\fP = 1200"
.br
.ti -1c
.RI "static final double \fBSUELDO_CAJER\fP = 1300"
.br
.ti -1c
.RI "static final double \fBSUELDO_ENCAR\fP = 1500"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La interfaz \fBContratable\fP expone los principales metodos del calculo de la nómina\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "double es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Contratable\&.getAportaciones ()"
Calcula y devuelve las aportaciones salariales del empresario en la nomina de un empleado\&. 
.PP
\fBDevuelve\fP
.RS 4
Un double con las aportaciones 
.RE
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro 
.RE
.PP

.PP
Implementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.
.SS "double es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Contratable\&.getIndemnizacion (\fBTipoDespido\fP tipo)"
Calcula y devuelve el salario neto de un empleado\&. 
.PP
\fBDevuelve\fP
.RS 4
Un double con la indemnizacion 
.RE
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro 
.RE
.PP

.PP
Implementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.
.SS "double es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Contratable\&.getSalarioBruto ()"
Calcula y devuelve el salario bruto de un empleado\&. 
.PP
\fBDevuelve\fP
.RS 4
Un double con el salarioBruto 
.RE
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro 
.RE
.PP

.PP
Implementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.
.SS "double es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Contratable\&.getSalarioNeto ()"
Calcula y devuelve el salario neto de un empleado\&. 
.PP
\fBDevuelve\fP
.RS 4
Un double con el salarioNeto 
.RE
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro 
.RE
.PP

.PP
Implementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
