.TH "es.etg.daw.prog.mercadaw.model.util.input.Fichero" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.input.Fichero
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroImp\fP y \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroMock\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBescribir\fP (String fichero, String texto)"
.br
.ti -1c
.RI "byte[] \fBleer\fP (String fichero)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Esta interface nos permite escribir y leer un fichero de forma binaria\&. 
.PP
\fBAutor\fP
.RS 4
: Iván Rafael Redondo 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
