.TH "es.etg.daw.prog.mercadaw.model.entities.ProductoTest" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.ProductoTest
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBtestCrearProducto\fP ()  throws MercaDAWException"
.br
.ti -1c
.RI "void \fBtestCalcularIva\fP ()  throws MercaDAWException"
.br
.ti -1c
.RI "void \fBtestPesoMinimo\fP ()  throws MercaDAWException"
.br
.ti -1c
.RI "void \fBtestAlturaMaxima\fP ()  throws MercaDAWException"
.br
.ti -1c
.RI "void \fBtestAnchuraMinima\fP ()  throws MercaDAWException"
.br
.ti -1c
.RI "void \fBtestNumElementosMax\fP ()  throws MercaDAWException"
.br
.ti -1c
.RI "void \fBtestPrecioFinal\fP ()  throws MercaDAWException"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
