.TH "es.etg.daw.prog.mercadaw.model.util.input.FicheroMock" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.input.FicheroMock
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.Fichero\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBescribir\fP (String ruta, String texto)"
.br
.ti -1c
.RI "byte[] \fBleer\fP (String fichero)"
.br
.in -1c
.SH "Documentación de las funciones miembro"
.PP 
.SS "void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroMock\&.escribir (String ruta, String texto)"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.Fichero\fP\&.
.SS "byte[] es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroMock\&.leer (String fichero)"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.Fichero\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
