.TH "es.etg.daw.prog.mercadaw.model.bbdd.Database" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.bbdd.Database
.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBORACLE\fP"
.br
.ti -1c
.RI "\fBMOCK\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La enumeración \fBMercaDAOFactory\fP posee las posibles BD disponibles\&. 
.PP
\fBAutor\fP
.RS 4
Jesús Pérez Enríquez\&. 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
