.TH "es.etg.daw.prog.mercadaw.view.sistema.CargaDatosViewController" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.view.sistema.CargaDatosViewController
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.ViewController\fP\&.
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static final String \fBNOMBRE_VENTANA\fP = 'Seleccionar Archivo'"
.br
.ti -1c
.RI "static final String \fBEXTENSION_CSV\fP = '*\&.csv'"
.br
.ti -1c
.RI "static final String \fBEXTENSION_SQL\fP = '*\&.sql'"
.br
.ti -1c
.RI "static final String \fBEXTENSION_JSON\fP = '*\&.json'"
.br
.ti -1c
.RI "static final String \fBDESC_CSV\fP = 'CSV'"
.br
.ti -1c
.RI "static final String \fBDESC_SQL\fP = 'SQL'"
.br
.ti -1c
.RI "static final String \fBDESC_JSON\fP = 'JSON'"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
\fBVista\fP de la carga de datos del sistema\&. 
.PP
\fBAutor\fP
.RS 4
Erik Herrera Llamas 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
