.TH "es.etg.daw.prog.mercadaw.model.entities.empleados.Cajero" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.empleados.Cajero
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCajero\fP (Integer id, String nombre, String apellidos, Date fechaInicio)"
.br
.ti -1c
.RI "double \fBgetSueldo\fP ()"
.br
.ti -1c
.RI "void \fBsetSueldo\fP (double sueldo)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
La clase \fBCajero\fP representa un cajero de MercaDAW\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP

.SH "Documentación del constructor y destructor"
.PP 
.SS "es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Cajero\&.Cajero (Integer id, String nombre, String apellidos, Date fechaInicio)"
Constructor que inicializa cajeros, generando el ID de estas automaticamente\&. 
.PP
\fBParámetros\fP
.RS 4
\fIId\fP del empleado 
.br
\fINombre\fP del empleado 
.br
\fIApellidos\fP del empleado 
.br
\fIFecha\fP de contratación del empleado 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "double es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Cajero\&.getSueldo ()"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.
.SS "void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Cajero\&.setSueldo (double sueldo)"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.
.SS "String es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Cajero\&.toString ()"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.empleados\&.Empleado\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
