.TH "es.etg.daw.prog.mercadaw.model.entities.empleados.TipoEmpleado" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.empleados.TipoEmpleado
.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBEMPLEADO\fP"
.br
.ti -1c
.RI "\fBREPONEDOR\fP"
.br
.ti -1c
.RI "\fBCAJERO\fP"
.br
.ti -1c
.RI "\fBENCARGADO\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La enumeracion \fBTipoEmpleado\fP representa los tipos de empleados de MercaDAW\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
