.TH "es.etg.daw.prog.mercadaw.model.util.FicheroBinarioTest" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.FicheroBinarioTest
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBleerEscribirTest\fP ()  throws Exception "
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
