.TH "es.etg.daw.prog.mercadaw.model.util.input.FicheroImp" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.input.FicheroImp
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.Fichero\fP\&.
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroBinario\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBescribir\fP (String ruta, String texto)"
.br
.ti -1c
.RI "byte[] \fBleer\fP (String fichero)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase abstracta \fBFicheroImp\fP utiliza \fBFichero\fP, pero no las implementa, si no que permite la herencia para que cada clase los pueda implementar como deba\&. 
.PP
\fBAutor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroImp\&.escribir (String ruta, String texto)"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.Fichero\fP\&.
.SS "byte[] es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroImp\&.leer (String fichero)"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.Fichero\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
