.TH "es.etg.daw.prog.mercadaw.model.util.export.Util" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.export.Util
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.ExportableUtil\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBexportar\fP (String nombreArcSal, String nombreArcEnt, String extension, String rutaArcEnt)  throws Exception"
.br
.ti -1c
.RI "String \fBgetUser\fP ()  throws Exception"
.br
.ti -1c
.RI "String \fBgetGrupo\fP ()  throws Exception"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase \fBUtil\fP sirve para exportar un documento usando pandoc y getUser() y getGrupo()\&. 
.PP
\fBAutor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.Util\&.exportar (String nombreArcSal, String nombreArcEnt, String extension, String rutaArcEnt) throws Exception"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.ExportableUtil\fP\&.
.SS "String es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.Util\&.getGrupo () throws Exception"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.ExportableUtil\fP\&.
.SS "String es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.Util\&.getUser () throws Exception"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.ExportableUtil\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
