.TH "es.etg.daw.prog.mercadaw.model.entities.productos.Producible" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.productos.Producible
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.productos\&.Producto\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "double \fBgetPrecioVenta\fP ()"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static final int \fBPESO_MIN\fP = 1"
.br
.ti -1c
.RI "static final int \fBPESO_MAX\fP = 5"
.br
.ti -1c
.RI "static final double \fBALTURA_MIN\fP = 0\&.5"
.br
.ti -1c
.RI "static final double \fBANCHURA_MIN\fP = 0\&.5"
.br
.ti -1c
.RI "static final double \fBIVA_ALIM\fP = 0\&.04"
.br
.ti -1c
.RI "static final double \fBIVA_COSM\fP = 0\&.10"
.br
.ti -1c
.RI "static final double \fBIVA_DROG\fP = 0\&.21"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La interfaz \fBProducible\fP expone los principales metodos de calculo del precio de venta de los productos\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "double es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.productos\&.Producible\&.getPrecioVenta ()"
Calcula em precio de venta de un producto\&. 
.PP
\fBDevuelve\fP
.RS 4
Un double con el precio final de venta del 
.RE
.PP

.PP
Implementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.productos\&.Producto\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
