.TH "es.etg.daw.prog.mercadaw.model.entities.productos.Recargos" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.productos.Recargos
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "double \fBgetRecargo\fP ()"
.br
.ti -1c
.RI "void \fBsetRecargo\fP (double recargo)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBRECARGO_15\fP =(0\&.15)"
.br
.ti -1c
.RI "\fBRECARGO_10\fP =(0\&.10)"
.br
.ti -1c
.RI "\fBRECARGO_5\fP =(0\&.05)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La enumeracion \fBRecargos\fP representa los recargos posibles y su valor correspondiente\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
