.TH "es.etg.daw.prog.mercadaw.controller.MercaDAWController" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.controller.MercaDAWController
.SH SYNOPSIS
.br
.PP
.PP
Herencias Application\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBstart\fP (Stage stage)  throws Exception "
.br
.ti -1c
.RI "void \fBcargarProductos\fP ()"
.br
.ti -1c
.RI "void \fBcargarEmpleados\fP ()"
.br
.ti -1c
.RI "void \fBcargarCompras\fP ()"
.br
.ti -1c
.RI "void \fBcargarImportar\fP ()"
.br
.ti -1c
.RI "void \fBcargarExportar\fP ()"
.br
.ti -1c
.RI "void \fBcargarApp\fP ()"
.br
.ti -1c
.RI "void \fBimportar\fP (String ruta)"
.br
.ti -1c
.RI "void \fBgetEmpleados\fP (\fBEmpleado\fP empleado)  throws SQLException, MercaDAWException "
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static final String \fBMSG_ERROR\fP = 'ERROR'"
.br
.ti -1c
.RI "static Stage \fBcurrentStage\fP"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
