.TH "es.etg.daw.prog.mercadaw.model.bbdd.MercaDAOImpOracleXETest" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.bbdd.MercaDAOImpOracleXETest
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBiniciarBBDDTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBinsertarEmpleadoTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBinsertarProductoTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBinsertarClienteTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBinsertarCompraTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBvisualizarClienteTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBvisualizarClientesTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBvisualizarEmpleadosTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBvisualizarProductoTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBvisualizarProductosTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBvisualizarComprasTest\fP ()  throws Exception"
.br
.ti -1c
.RI "void \fBborrarTablas\fP ()  throws Exception"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
