.TH "es.etg.daw.prog.mercadaw.model.entities.productos.Porcentajes" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.productos.Porcentajes
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "double \fBgetPorcentaje\fP ()"
.br
.ti -1c
.RI "void \fBsetPorcentaje\fP (double porcentaje)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBPORCENTAJE_5\fP =(5)"
.br
.ti -1c
.RI "\fBPORCENTAJE_10\fP =(10)"
.br
.ti -1c
.RI "\fBPORCENTAJE_15\fP =(15)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La enumeracion \fBRecargos\fP representa los porcentajes posibles y su valor correspondiente\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
