.TH "es.etg.daw.prog.mercadaw.view.compra.DarAltaCompraViewController" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.view.compra.DarAltaCompraViewController
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.ViewController\fP\&.
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
\fBVista\fP de dar alta compra\&. 
.PP
\fBAutor\fP
.RS 4
Erik Herrera Llamas 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
