.TH "es.etg.daw.prog.mercadaw.model.util.export.ExportableUtil" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.export.ExportableUtil
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.export\&.Util\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBexportar\fP (String nombreArcSal, String nombreArcEnt, String extension, String rutaArcEnt)  throws Exception"
.br
.ti -1c
.RI "String \fBgetUser\fP ()  throws Exception"
.br
.ti -1c
.RI "String \fBgetGrupo\fP ()  throws Exception"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La interfaz \fBExportableUtil\fP nos permitira que la clase \fBUtil\fP pueda exportar con cualquier tipo de extensión\&. 
.PP
\fBAutor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
