.TH "es.etg.daw.prog.mercadaw.model.bbdd.MarcaDAOImp" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.bbdd.MarcaDAOImp
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpOracleXE\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "abstract void \fBcrearEmpleados\fP (Statement st)  throws SQLException"
.br
.ti -1c
.RI "abstract void \fBcrearClientes\fP (Statement st)  throws SQLException"
.br
.ti -1c
.RI "abstract void \fBcrearCompras\fP (Statement st)  throws SQLException"
.br
.ti -1c
.RI "abstract void \fBcrearProductos\fP (Statement st)  throws SQLException"
.br
.ti -1c
.RI "Connection \fBgetConnection\fP ()"
.br
.ti -1c
.RI "void \fBsetConnection\fP (Connection connection)"
.br
.in -1c
.SS "Atributos protegidos"

.in +1c
.ti -1c
.RI "Connection \fBconnection\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase MercaDAOImp servirá para futuras actualizaciones\&. 
.PP
\fBAutor\fP
.RS 4
Jesús Pérez Enríquez\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "abstract void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MarcaDAOImp\&.crearClientes (Statement st) throws SQLException\fC [abstract]\fP"

.PP
Reimplementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpOracleXE\fP\&.
.SS "abstract void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MarcaDAOImp\&.crearCompras (Statement st) throws SQLException\fC [abstract]\fP"

.PP
Reimplementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpOracleXE\fP\&.
.SS "abstract void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MarcaDAOImp\&.crearEmpleados (Statement st) throws SQLException\fC [abstract]\fP"

.PP
Reimplementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpOracleXE\fP\&.
.SS "abstract void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MarcaDAOImp\&.crearProductos (Statement st) throws SQLException\fC [abstract]\fP"

.PP
Reimplementado en \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpOracleXE\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
