.TH "es.etg.daw.prog.mercadaw.model.util.reader.LectorImp" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.reader.LectorImp
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorCSV\fP y \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorJSON\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "abstract List< \fBProducto\fP > \fBleerProducto\fP (String codigo)  throws MercaDAWException"
.br
.ti -1c
.RI "abstract List< \fBEmpleado\fP > \fBleerEmpleado\fP (String codigo)  throws MercaDAWException"
.br
.ti -1c
.RI "abstract List< \fBCliente\fP > \fBleerCliente\fP (String codigo)  throws MercaDAWException"
.br
.ti -1c
.RI "abstract List< \fBCompra\fP > \fBleerCompra\fP (String codigo)  throws MercaDAWException"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase abstracta \fBLectorImp\fP utiliza \fBLector\fP, pero sin implementarla, esta clase sirve para poder tener hijas para que cad auan las implemente como deba\&. 
.PP
\fBAutor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "abstract List< \fBCliente\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\&.leerCliente (String codigo) throws \fBMercaDAWException\fP\fC [abstract]\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.SS "abstract List< \fBCompra\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\&.leerCompra (String codigo) throws \fBMercaDAWException\fP\fC [abstract]\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.SS "abstract List< \fBEmpleado\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\&.leerEmpleado (String codigo) throws \fBMercaDAWException\fP\fC [abstract]\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.SS "abstract List< \fBProducto\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\&.leerProducto (String codigo) throws \fBMercaDAWException\fP\fC [abstract]\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
