.TH "es.etg.daw.prog.mercadaw.model.util.reader.LectorCSV" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.reader.LectorCSV
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "List< \fBProducto\fP > \fBleerProducto\fP (String codigo)  throws MercaDAWException "
.br
.ti -1c
.RI "List< \fBEmpleado\fP > \fBleerEmpleado\fP (String codigo)  throws MercaDAWException "
.br
.ti -1c
.RI "List< \fBCliente\fP > \fBleerCliente\fP (String codigo)  throws MercaDAWException "
.br
.ti -1c
.RI "List< \fBCompra\fP > \fBleerCompra\fP (String codigo)  throws MercaDAWException "
.br
.ti -1c
.RI "void \fBcomprobar\fP (String cadena)  throws MercaDAWException "
.br
.ti -1c
.RI "\fBProducto\fP \fBprocesarProducto\fP (String fila)  throws MercaDAWException "
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase \fBLectorCSV\fP utiliza la inetrfaz LectorIMp para poder leer los entities y poder procesarlos\&. 
.PP
\fBAutor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "List< \fBCliente\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorCSV\&.leerCliente (String codigo) throws \fBMercaDAWException\fP"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\fP\&.
.SS "List< \fBCompra\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorCSV\&.leerCompra (String codigo) throws \fBMercaDAWException\fP"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\fP\&.
.SS "List< \fBEmpleado\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorCSV\&.leerEmpleado (String codigo) throws \fBMercaDAWException\fP"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\fP\&.
.SS "List< \fBProducto\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorCSV\&.leerProducto (String codigo) throws \fBMercaDAWException\fP"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorImp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
