.TH "es.etg.daw.prog.mercadaw.view.Vista" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.view.Vista
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "String \fBgetRuta\fP ()"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "\fBMAIN\fP =('view/MainView\&.fxml')"
.br
.ti -1c
.RI "\fBCARGA_DATOS\fP =('view/sistema/CargaDatosView\&.fxml')"
.br
.ti -1c
.RI "\fBEXPORTAR_DATOS\fP =('view/sistema/ExportarDatosView\&.fxml')"
.br
.ti -1c
.RI "\fBDAR_ALTA_PROD\fP =('view/producto/DarAltaProductoView\&.fxml')"
.br
.ti -1c
.RI "\fBDAR_ALTA_EMPLE\fP =('view/empleado/DarAltaEmpleadoView\&.fxml')"
.br
.ti -1c
.RI "\fBDAR_ALTA_COMP\fP =('view/compra/DarAltaCompraView\&.fxml')"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Esta clase contiene las rutas hacia las diferentes vistas de nuestra aplicación\&. 
.PP
\fBAutor\fP
.RS 4
Erik Herrera Llamas 
.RE
.PP
\fBVersión\fP
.RS 4
1\&.0 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
