.TH "es.etg.daw.prog.mercadaw.model.bbdd.MercaDAOFactory" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.bbdd.MercaDAOFactory
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static \fBMercaDAO\fP \fBobtener\fP (\fBDatabase\fP tipo)  throws SQLException"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase \fBMercaDAOFactory\fP crea las posibles BD disponibles\&. 
.PP
\fBAutor\fP
.RS 4
Jesús Pérez Enríquez\&. 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
