.TH "es.etg.daw.prog.mercadaw.model.util.input.FicheroFactory" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.input.FicheroFactory
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static \fBFichero\fP \fBobtener\fP (\fBFormato\fP formato)"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
