.TH "es.etg.daw.prog.mercadaw.model.util.CSVTest" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.CSVTest
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBcargarProducto\fP ()  throws MercaDAWException "
.br
.ti -1c
.RI "void \fBcargarEmpleado\fP ()  throws MercaDAWException "
.br
.ti -1c
.RI "void \fBcargarCliente\fP ()  throws MercaDAWException "
.br
.ti -1c
.RI "void \fBcargarCadenaVaciaTestProducto\fP ()"
.br
.ti -1c
.RI "void \fBcargarVacioTestEmpelado\fP ()"
.br
.ti -1c
.RI "void \fBcargarVacioTestCliente\fP ()"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
