.TH "es.etg.daw.prog.mercadaw.model.entities.EmpleadoTest" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.EmpleadoTest
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBcreacionEmpleados\fP ()  throws MercaDAWException "
.br
.ti -1c
.RI "void \fBcrearEmpleadoTest\fP ()"
.br
.ti -1c
.RI "void \fBgetSueldoTest\fP ()"
.br
.ti -1c
.RI "void \fBgetPPETest\fP ()"
.br
.ti -1c
.RI "void \fBgetSalarioBrutoTest\fP ()"
.br
.ti -1c
.RI "void \fBgetDeduccionesTest\fP ()"
.br
.ti -1c
.RI "void \fBgetSalarioNetoTest\fP ()"
.br
.ti -1c
.RI "void \fBgetAportacionesTest\fP ()"
.br
.ti -1c
.RI "void \fBgetIndemnizacion\fP ()"
.br
.ti -1c
.RI "void \fBgetSalarioDiarioTest\fP ()"
.br
.ti -1c
.RI "void \fBgetIndemnizacionLegalTest\fP ()"
.br
.ti -1c
.RI "void \fBgetAntiguedadTest\fP ()"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
