.TH "es.etg.daw.prog.mercadaw.model.entities.compras.Cliente" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.compras.Cliente
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCliente\fP (Integer id, String nombre, String correo, int codPostal)"
.br
.ti -1c
.RI "Integer \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (Integer id)"
.br
.ti -1c
.RI "String \fBgetNombre\fP ()"
.br
.ti -1c
.RI "void \fBsetNombre\fP (String nombre)"
.br
.ti -1c
.RI "String \fBgetCorreo\fP ()"
.br
.ti -1c
.RI "void \fBsetCorreo\fP (String correo)"
.br
.ti -1c
.RI "int \fBgetCodPostal\fP ()"
.br
.ti -1c
.RI "void \fBsetCodPostal\fP (int codPostal)"
.br
.in -1c
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static int \fBgetNumClientes\fP ()"
.br
.ti -1c
.RI "static void \fBsetNumClientes\fP (int numClientes)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase \fBCliente\fP representa un cliente de MercaDAW\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP

.SH "Documentación del constructor y destructor"
.PP 
.SS "es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.compras\&.Cliente\&.Cliente (Integer id, String nombre, String correo, int codPostal)"
Constructor que inicializa clientes, generando el ID de estos automaticamente\&. 
.PP
\fBParámetros\fP
.RS 4
\fIid\fP 
.br
\fInombre\fP 
.br
\fIcorreo\fP 
.br
\fIcodPostal\fP 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
