.TH "es.etg.daw.prog.mercadaw.model.util.reader.LectorMock" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.reader.LectorMock
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "List< \fBProducto\fP > \fBleerProducto\fP (String codigo)  throws MercaDAWException "
.br
.ti -1c
.RI "List< \fBEmpleado\fP > \fBleerEmpleado\fP (String codigo)  throws MercaDAWException "
.br
.ti -1c
.RI "List< \fBCliente\fP > \fBleerCliente\fP (String codigo)  throws MercaDAWException "
.br
.ti -1c
.RI "List< \fBCompra\fP > \fBleerCompra\fP (String codigo)  throws MercaDAWException "
.br
.in -1c
.SH "Documentación de las funciones miembro"
.PP 
.SS "List< \fBCliente\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorMock\&.leerCliente (String codigo) throws \fBMercaDAWException\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.SS "List< \fBCompra\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorMock\&.leerCompra (String codigo) throws \fBMercaDAWException\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.SS "List< \fBEmpleado\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorMock\&.leerEmpleado (String codigo) throws \fBMercaDAWException\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.
.SS "List< \fBProducto\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.LectorMock\&.leerProducto (String codigo) throws \fBMercaDAWException\fP"

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.reader\&.Lector\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
