.TH "es.etg.daw.prog.mercadaw.model.util.input.FicheroBinario" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.util.input.FicheroBinario
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroImp\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBescribir\fP (String ruta, String texto)"
.br
.ti -1c
.RI "byte[] \fBleer\fP (String fichero)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Clase \fBFicheroBinario\fP que utiliza la interfaz \fBFicheroImp\fP para sobreescribir los métodos para leer y escribir en binario\&. 
.PP
\fBAutor\fP
.RS 4
Iván Rafael Redondo\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroBinario\&.escribir (String ruta, String texto)"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroImp\fP\&.
.SS "byte[] es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroBinario\&.leer (String fichero)"

.PP
Reimplementado de \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.util\&.input\&.FicheroImp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
