.TH "es.etg.daw.prog.mercadaw.model.entities.compras.Compra" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.compras.Compra
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCompra\fP (Integer id, Date fecha, \fBCliente\fP cliente, List< \fBProducto\fP > productos)"
.br
.ti -1c
.RI "Date \fBgetFecha\fP ()"
.br
.ti -1c
.RI "void \fBsetFecha\fP (Date fecha)"
.br
.ti -1c
.RI "\fBCliente\fP \fBgetCliente\fP ()"
.br
.ti -1c
.RI "void \fBsetCliente\fP (\fBCliente\fP cliente)"
.br
.ti -1c
.RI "List< \fBProducto\fP > \fBgetProductos\fP ()"
.br
.ti -1c
.RI "void \fBsetProductos\fP (List< \fBProducto\fP > productos)"
.br
.ti -1c
.RI "Integer \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (Integer id)"
.br
.in -1c
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static int \fBgetNumCompras\fP ()"
.br
.ti -1c
.RI "static void \fBsetNumCompras\fP (int numCompras)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase \fBCompra\fP representa las compras realizadas por los clientes de MercaDAW\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP

.SH "Documentación del constructor y destructor"
.PP 
.SS "es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.compras\&.Compra\&.Compra (Integer id, Date fecha, \fBCliente\fP cliente, List< \fBProducto\fP > productos)"
Constructor que inicializa compras, generando el ID de estas automaticamente\&. 
.PP
\fBParámetros\fP
.RS 4
\fIid\fP 
.br
\fIfecha\fP 
.br
\fIcliente\fP 
.br
\fIproductos\fP 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
