.TH "es.etg.daw.prog.mercadaw.model.entities.productos.Cosmetica" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.entities.productos.Cosmetica
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.productos\&.Producto\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCosmetica\fP (Integer id, String nombre, String marca, double altura, double anchura, double peso, int numElementos, int stock, double precio, String descripcion)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
La clase \fBCosmetica\fP representa un producto de cosmética de MercaDAW\&. 
.PP
\fBAutor\fP
.RS 4
Diego Madroñero Chamorro\&. 
.RE
.PP

.SH "Documentación del constructor y destructor"
.PP 
.SS "es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.entities\&.productos\&.Cosmetica\&.Cosmetica (Integer id, String nombre, String marca, double altura, double anchura, double peso, int numElementos, int stock, double precio, String descripcion)"
Constructor que inicializa productos de cosmética, generando el ID de estos automaticamente\&. 
.PP
\fBParámetros\fP
.RS 4
\fIID\fP del producto 
.br
\fINombre\fP del producto 
.br
\fIMarca\fP del producto 
.br
\fIAltura\fP del producto 
.br
\fIAnchura\fP del producto 
.br
\fIPeso\fP del producto 
.br
\fINumero\fP de elementos del producto 
.br
\fIStock\fP del producto 
.br
\fIPrecio\fP del producto 
.br
\fIDescripcion\fP del producto 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
