.TH "es.etg.daw.prog.mercadaw.model.bbdd.MercaDAOImpMock" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.model.bbdd.MercaDAOImpMock
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBiniciarBBDD\fP ()  throws SQLException "
.br
.ti -1c
.RI "int \fBinsertar\fP (\fBEmpleado\fP emp)  throws SQLException "
.br
.ti -1c
.RI "int \fBinsertar\fP (\fBProducto\fP prod)  throws SQLException "
.br
.ti -1c
.RI "int \fBinsertar\fP (\fBCompra\fP compra)  throws SQLException "
.br
.ti -1c
.RI "int \fBinsertar\fP (\fBCliente\fP client)  throws SQLException "
.br
.ti -1c
.RI "\fBProducto\fP \fBvisualizarProducto\fP (int id)  throws MercaDAWException"
.br
.ti -1c
.RI "List< \fBProducto\fP > \fBvisualizarProductos\fP ()  throws MercaDAWException"
.br
.ti -1c
.RI "\fBCliente\fP \fBvisualizarCliente\fP (int id)"
.br
.ti -1c
.RI "List< \fBCliente\fP > \fBvisualizarClientes\fP ()"
.br
.ti -1c
.RI "List< \fBEmpleado\fP > \fBvisualizarEmpleados\fP ()  throws MercaDAWException "
.br
.ti -1c
.RI "List< \fBCompra\fP > \fBvisualizarCompras\fP ()  throws MercaDAWException "
.br
.in -1c
.SH "Descripción detallada"
.PP 
La clase \fBMercaDAOImpMock\fP provee de datos de prueba para el desarrollo del software\&. 
.PP
\fBAutor\fP
.RS 4
Jesús Pérez Enríquez\&. 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "void es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.iniciarBBDD () throws SQLException"
Prepara la base de datos\&. (Crea las tablas y vistas)\&. 
.PP
\fBExcepciones\fP
.RS 4
\fISQLException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "int es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.insertar (\fBCliente\fP client) throws SQLException"
Inserta el Cliente en la Base de datos\&. 
.PP
\fBParámetros\fP
.RS 4
\fIclient\fP Cliente a insertar\&. 
.RE
.PP
\fBDevuelve\fP
.RS 4
int Numero de insercciones completadas\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "int es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.insertar (\fBCompra\fP compra) throws SQLException"
Inserta la Compra en la Base de datos\&. 
.PP
\fBParámetros\fP
.RS 4
\fIcompra\fP Compra a insertar\&. 
.RE
.PP
\fBDevuelve\fP
.RS 4
int Numero de insercciones completadas\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "int es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.insertar (\fBEmpleado\fP emp) throws SQLException"
Inserta el Empleado en la Base de datos\&. 
.PP
\fBParámetros\fP
.RS 4
\fIempleado\fP Empleado a insertar\&. 
.RE
.PP
\fBDevuelve\fP
.RS 4
int Numero de insercciones completadas\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "int es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.insertar (\fBProducto\fP prod) throws SQLException"
Inserta el Producto en la Base de datos\&. 
.PP
\fBParámetros\fP
.RS 4
\fIproducto\fP Producto a insertar\&. 
.RE
.PP
\fBDevuelve\fP
.RS 4
int Numero de insercciones completadas\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "\fBCliente\fP es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.visualizarCliente (int id)"
Visualiza el Cliente con la id del parametro\&. 
.PP
\fBParámetros\fP
.RS 4
\fIid\fP Id del Cliente que quieres\&. 
.RE
.PP
\fBDevuelve\fP
.RS 4
Cliente El cliente con la id del parametro\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "List< \fBCliente\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.visualizarClientes ()"
Devuelve la lista de Clientes de la BD completa\&. 
.PP
\fBDevuelve\fP
.RS 4
List<Cliente> Los clientes de la BD\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "List< \fBCompra\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.visualizarCompras () throws \fBMercaDAWException\fP"
Devuelve la lista de Compras de la BD completa\&. 
.PP
\fBDevuelve\fP
.RS 4
List<Compra> Las compas de la BD\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException,MercaDAWException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "List< \fBEmpleado\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.visualizarEmpleados () throws \fBMercaDAWException\fP"
Devuelve la lista de Empleados de la BD completa\&. 
.PP
\fBDevuelve\fP
.RS 4
List<Empleado> Los empleados de la BD\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException,MercaDAWException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "\fBProducto\fP es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.visualizarProducto (int id) throws \fBMercaDAWException\fP"
Hace un select a la BD con la id pasada\&. 
.PP
\fBParámetros\fP
.RS 4
\fIid\fP Id del producto que quieres\&. 
.RE
.PP
\fBDevuelve\fP
.RS 4
Producto con la id pasada por\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException,MercaDAWException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.
.SS "List< \fBProducto\fP > es\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAOImpMock\&.visualizarProductos () throws \fBMercaDAWException\fP"
Devuelve la lista de Productos de la BD completa\&. 
.PP
\fBDevuelve\fP
.RS 4
List<Producto> Los productos de la BD\&. 
.RE
.PP
\fBExcepciones\fP
.RS 4
\fISQLException,MercaDAWException\fP 
.RE
.PP

.PP
Implementa \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.model\&.bbdd\&.MercaDAO\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
