.TH "es.etg.daw.prog.mercadaw.view.ViewController" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.etg.daw.prog.mercadaw.view.ViewController
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.MainViewController\fP, \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.compra\&.DarAltaCompraViewController\fP, \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.empleado\&.DarAltaEmpleadoViewController\fP, \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.producto\&.DarAltaProductoViewController\fP, \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.sistema\&.CargaDatosViewController\fP y \fBes\&.etg\&.daw\&.prog\&.mercadaw\&.view\&.sistema\&.ExportarDatosViewController\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBsetMercaDAWController\fP (\fBMercaDAWController\fP mercaDAWController)"
.br
.in -1c
.SS "Atributos protegidos"

.in +1c
.ti -1c
.RI "\fBMercaDAWController\fP \fBmercaDAWController\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Esta clase es la que nos permite la comunicación entre las vistas y el controlador de la aplicación\&. 
.PP
\fBAutor\fP
.RS 4
Erik Herrera Llamas\&. 
.RE
.PP
\fBVersión\fP
.RS 4
1\&.0 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para MercaDAW del código fuente\&.
