.TH "md__home_usuario__documentos_mercadaw_trabajo_ev3_analisis__analisis" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_usuario__documentos_mercadaw_trabajo_ev3_analisis__analisis \- Práctica 3ª Evaluación 

.SH "# Análisis"
.PP
.SH "Requisitos Funcionales y No Funcionales"
.PP
.SS "Requisitos Funcionales"
.IP "1." 4
Cargar datos del sistema
.IP "2." 4
Dar de alta un producto
.IP "3." 4
Dar de alta un empleado
.IP "4." 4
Consultar datos del producto
.IP "5." 4
Visualizar los empleados
.IP "6." 4
Dar de alta una compra
.IP "7." 4
Listado de compras
.IP "8." 4
Listado de stock
.IP "9." 4
Obtener precio venta
.IP "10." 4
Imprimir ticket
.IP "11." 4
Calcular nóminas
.IP "12." 4
Crear copias de seguridad
.IP "13." 4
Exportar de datos
.PP
.SS "Requisitos No Funcionales"
.IP "1." 4
Tipo moneda
.IP "2." 4
Tipos formato archivos para la carga de datos
.IP "3." 4
Tipos formato archivos para la exportación de datos
.IP "4." 4
Idioma
.PP
.SH "DESARROLLO CASO DE USO"
.PP
.SS "Gestionar Sistema"
.IP "1." 4
Cargar datos del sistema
.IP "12." 4
Crear copias de seguridad
.IP "13." 4
Exportar de datos
.PP
.SS "Gestionar Empleados"
.IP "3." 4
Dar de alta un empleado
.IP "5." 4
Visualizar los empleados
.IP "11." 4
Calcular nóminas
.PP
.SS "Gestionar Productos"
.IP "2." 4
Dar de alta un producto
.IP "4." 4
Consultar datos del producto
.IP "8." 4
Listado de stock
.IP "9." 4
Obtener precio venta
.IP "10." 4
Imprimir ticket
.PP
.SS "Gestionar Compras"
.IP "6." 4
Dar de alta una compra
.IP "7." 4
Listado de compras 
.PP

