.TH "md__home_usuario__documentos_mercadaw_trabajo_ev3__r_e_a_d_m_e" 3 "Domingo, 19 de Mayo de 2024" "MercaDAW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_usuario__documentos_mercadaw_trabajo_ev3__r_e_a_d_m_e \- Mercadaw Trabajo Programación 3Ev 
Trabajo de programación de la tercera evaluación de Erik Herrera, Iván Rafael, Jesús Pérez y Diego Madroñero
.SH "Información Diseño"
.PP
En el Diagrama de Despliegue, el device Docker está fuera de la máquina usuario porque es un servidor al que se pueden conectar más usuarios a la misma BBDD\&. 
