@startuml MercaDAW

package model{
    package entities {
        package productos{
            enum TipoProducto{
                ALIMENTACION, DROGUERIA, COSMETICA
            }

            class ProductoFactory{
                + {static} obtenerProducto(tipo: TipoProducto):Producible    
            }

            interface Producible{
                + getPrecioVenta(Producto p): double
            }

            abstract class Producto {
                - nombre: String
                - marca: String
                - precio: double
                - iva: double
                - altura: double
                - anchura: double
                - peso: double
                - numElementos: int
                - descripcion: String

                + Producto(builder: ProductoBuilder)
                + {static} builder(): ProductoBuilder
            }

            class Alimentacion {
                - iva: double
            }

            class Drogueria {
                - iva: double
            }

            class Cosmetica {
                - iva: double
            }

            class ProductoBuilder {
                - nombre: String
                - marca: String
                - precio: double
                - iva: double
                - altura: double
                - anchura: double
                - peso: double
                - numElementos: int
                - descripcion: String

                + setNombre(nom: String): ProductoBuilder
                + setMarca(marca: String): ProductoBuilder
                + setCategoria(cat: int): ProductoBuilder
                + setPrecio(precio: double): ProductoBuilder
                + setIva(iva: int): ProductoBuilder
                + setAltura(alt: double): ProductoBuilder
                + setAnchura(anch: double): ProductoBuilder
                + setPeso(peso: double): ProductoBuilder
                + setNumElementos(numElem: int): ProductoBuilder
                + setDescripcion(desc: String): ProductoBuilder
                ProductoBuilder()
                + build(): Producto
            }

            Producible <|.. Producto
            Producto <|-- Alimentacion
            Producto <|-- Drogueria
            Producto <|-- Cosmetica

        }

        package empleados {
            interface Contratable {
                + calcularNomina();
            }

            class EmpleadoFactory{
                {static} crear(E):Contratable
            }

            class EmpleadoBuilder {
                - id: int
                - nombre: String
                - apellidos: String
                - categoria: CategoriaEmpleado
                - sueldo: double
                + setId(id: int): int
                + setNombre(nom: String): String
                + setApellidos(ape: String): String
                + setCategoria(cat: CategoriaEmpleado): CategoriaEmpleado
                + setSueldo(sueldo: double): double
                EmpleadoBuilder()
                + build(): Empleado
            }

            class Empleado {
                + SUELDO: double = 1000

                - id: int
                - nombre: String
                - apellidos: String
                - categoria: CategoriaEmpleado
                - sueldo: double
                + Empleado(builder: EmpleadoBuilder)
                + {static} builder(): EmpleadoBuilder
            }

            class Reponedor {
                + SUELDO: double = 1200

                - sueldo: double
            }

            class Cajero {
                + SUELDO: double = 1300

                - sueldo: double
            }

            class Encargado {
                + SUELDO: double = 1500

                - sueldo: double
            }

            Contratable <|.. Empleado
            Empleado <|-- Encargado
            Empleado <|-- Reponedor
            Empleado <|-- Cajero
        }

        package clientes {
            class Cliente {
                - nombre: String 
                - correo: String 
                - codPostal: String
            }

            class Compra {
                - fecha: Date
            }
        }
    }
}
@enduml