@startuml export

set separator none
package es.etg.daw.prog.mercadaw.model.util.export{


    class Util{

    }

    interface ExportableUtil{

        + exportar(ruta:String): void
        + getUser(): String
        + getGrupo(): String
    }

    interface Documento{
        + getContenido:Map<String, Object[]>
        + getTitulo():String
        + getPie():String
    }
}

package es.etg.daw.prog.mercadaw.model.entity{
    class MercaDAW
}


ExportableUtil <|.. Util
Documento <|.. MercaDAW

@enduml

