@startuml export

set separator none
package es.etg.daw.prog.mercadaw.model.util.export{


    class Util{
        +  public void exportar(String nombreArcSal, String nombreArcEnt, String extension, String rutaArcEnt)
    }

    interface ExportableUtil{

        + exportar(ruta:String): void
        + getUser(): String
        + getGrupo(): String
    }


}


ExportableUtil <|.. Util


@enduml

