@startuml input

set separator none
package es.etg.daw.prog.mercadaw.model.util.input{

    enum Formato{
        BINARIO, MOCKs
    }

    class FicheroFactory{
        {static} + obtenerFicheroBinario():Fichero
    }

    class FicheroMock{

    }

    class FicheroBinario{

    }

    abstract FicheroImp{

    }

    interface Fichero{
        + leer(): byte[]

    }
}


FicheroImp <|-- FicheroBinario
FicheroMock ..|> Fichero
FicheroImp ..|> Fichero
@enduml