@startuml export
set separator none
package es.etg.daw.prog.mercadaw.model.util.export{
    
    enum Exportable{
        PDF, EXCEL, OTRO
    }

    class PDFUtil{

    }

    class ExcelUtil{

    }

    abstract Util{
        + crearFichero(exportable:Exportable): byte[]
    }

    interface ExportableUtil{
        + crearFichero(exportable:Exportable): byte[]
    }

    class DocumentoFactory{
       {static} obtenerExport(tipo:Tipo): Exportable
    }

    interface Documento{
        + getContenido:Map<String, Object[]>
        + getTitulo():String
        + getPie():String
    }
}

package es.etg.daw.prog.mercadaw.model.entity{
    class MercaDAW
}




Util <|-- PDFUtil
Util <|-- ExcelUtil
ExportableUtil <|.. Util 
Documento <|.. MercaDAW

@enduml

