@startuml disenyo
    package model{
        package bbdd{
            enum Database{
                ORACLE XE, MOCK
            }
            interface MercaDAO{
            + crearTablaEmpleado()
            + crearTablaProducto()
            + insertar(Empleado empleado)
            + insertar(Producto producto)
            + actualizar(Empleado empleado)
            + actualizar(Producto producto)
            + borrar(Empleado empleado)
            + borrar(Producto producto)
            + visualizarProductos():List<Producto>
            + visualizarEmpleados():List<Empleado>
            }

            class MercadoDBFactory{
                {static} obtener(d:database): MercaDAO
            }

            abstract MercaDAOImp {
                  # connection: Connection
               
                
            }

            class MercaDAOImpMock{

            }

            class MercaDAOImpOracleXE{
              
            }
       
        }
           
    }

    MercaDAOImp <|-- MercaDAOImpOracleXE
    MercaDAOImp..|> MercaDAO
    MercaDAOImpMock..|> MercaDAO 
    


@enduml