@startuml Diag Componentes 

component view
component controller
component model 

view ..> controller
controller ..> model

@enduml

@startuml disenyo
allow_mixing
top to bottom direction
package view{

    component View <<FXML file>>

    component ViewController <<java>>
}

package controller{
    component MercaDAWController <<java>>

}

package model{

    package bbdd{
        component Database <<java>>

        interface MercaDAO{

        }
    }

    package util{
        component Reader <<java>>
          interface Lector {

          }
        component Input <<java>>
          interface Fichero {

          }

    }

    package exception{
        component MercaDAWException <<java>>
    }


    ViewController ..> View: use

    ViewController ..> MercaDAWController: use

    MercaDAWController ..> MercaDAO: use
    MercaDAWController ..> Lector: use
    MercaDAWController ..> Fichero: use
    MercaDAWController ..> MercaDAWException: use


    MercaDAO <|.. Database  
    Lector <|.. Reader  
    Fichero <|.. Input  


}

@enduml