@startuml Casos Uso
left to right direction
actor Empleado as emp

rectangle MercaDaw {
    usecase "Gestionar Empleados" as uc_1
    usecase "Gestionar Productos" as uc_2
    usecase "Gestionar Compras" as uc_3
    usecase "Gestionar Sistema" as uc_4
}

emp -- uc_1
emp -- uc_2
emp -- uc_3
emp -- uc_4
@enduml
